### ISSUE TITLE
Bert Demo Error(s)

### ISSUE THREAD

**Issue by danindiana** [tenstorrent/tt-buda-demos#50]
**Describe the bug**
Errors encountered when attempting to run the Bert NLP demo.

**To Reproduce**
from:https://github.com/tenstorrent/tt-buda-demos/blob/main/first_5_steps/2_running_nlp_models.ipynb

python3 --version
Python 3.8.10
python3 bert_buda.py 

**Expected behavior**

**Screenshots**
![Screenshot_2024-04-16_05-32-51](https://github.com/tenstorrent/tt-buda-demos/assets/3030588/be0ce0e6-a0d3-48b3-bc0f-56691d248a74)
![Screenshot_2024-04-16_05-32-45](https://github.com/tenstorrent/tt-buda-demos/assets/3030588/ffffb795-999c-44f8-9294-1ca04742516d)

**System (please complete the following information):**
 - Device: [e.g. E150]
 - Version [e.g. v0.9.75]

OS: Ubuntu 20.04 focal
 Kernel: x86_64 Linux 5.15.0-102-generic
 Uptime: 46m
 Packages: 1950
 Shell: bash 5.0.17
 Disk: 27G / 1.9T (2%)
 CPU: AMD Ryzen 9 7950X3D 16-Core @ 32x 4.2GHz
 GPU: AMD/ATI
 RAM: 3278MiB / 192425MiB

![Screenshot_2024-04-16_05-29-55](https://github.com/tenstorrent/tt-buda-demos/assets/3030588/f7bca987-6527-4c0c-8160-8eaf4162c6c7)

**Additional context**

2024-04-16 05:21:39.757 | DEBUG    | pybuda.ttdevice:_create_intermediates_queue_device_connector:1421 - Creating fwd intermediates queue connector on TTDevice 'tt_device_0'
2024-04-16 05:21:39.757 | DEBUG    | pybuda.ttdevice:_create_forward_output_queue_device_connector:1401 - Creating forward output queue connector on TTDevice 'tt_device_0'
2024-04-16 05:21:39.757 | ERROR    | pybuda.run.impl:_start_device_processes:1180 - Process spawn error: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
2024-04-16 05:21:39.757 | DEBUG    | pybuda.run.impl:_shutdown:1265 - PyBuda shutdown
2024-04-16 05:21:39.757 | DEBUG    | pybuda.run.impl:_shutdown:1281 - Waiting until processes done
2024-04-16 05:21:39.757 | WARNING  | pybuda.tensor:pytorch_dtype_to_buda_dataformat:594 - Parameter is int64. Setting to int8 for now.
2024-04-16 05:21:39.757 | WARNING  | pybuda.tensor:pytorch_dtype_to_buda_dataformat:594 - Parameter is int64. Setting to int8 for now.
2024-04-16 05:21:39.757 | WARNING  | pybuda.tensor:pytorch_dtype_to_buda_dataformat:594 - Parameter is int64. Setting to int8 for now.
2024-04-16 05:21:39.757 | WARNING  | pybuda.tensor:pytorch_dtype_to_buda_dataformat:594 - Parameter is int64. Setting to int8 for now.
2024-04-16 05:21:39.757 | WARNING  | pybuda.tensor:pytorch_dtype_to_buda_dataformat:594 - Parameter is int64. Setting to int8 for now.
2024-04-16 05:21:39.758 | WARNING  | pybuda.tensor:pytorch_dtype_to_buda_dataformat:594 - Parameter is int64. Setting to int8 for now.
2024-04-16 05:21:39.858 | DEBUG    | pybuda.device:get_command_queue_response:311 - Ending process on CPUDevice 'cpu0_fallback' due to shutdown event
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/usr/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/smduck/Downloads/pyb/bert_buda.py", line 59, in <module>
    output_q = pybuda.run_inference()  # executes compilation (if first time) + runtime
  File "/home/smduck/Downloads/pyb-20-04/env/lib/python3.8/site-packages/pybuda/run/api.py", line 90, in run_inference
    return _run_inference(module, inputs, input_count, output_queue, _sequential, _perf_trace, _verify_cfg)
  File "/home/smduck/Downloads/pyb-20-04/env/lib/python3.8/site-packages/pybuda/run/impl.py", line 277, in _run_inference
    return _run_devices_inference(
  File "/home/smduck/Downloads/pyb-20-04/env/lib/python3.8/site-packages/pybuda/run/impl.py", line 467, in _run_devices_inference
    output_queue = _initialize_pipeline(False, output_queue, sequential=sequential, verify_cfg=verify_cfg)
  File "/home/smduck/Downloads/pyb-20-04/env/lib/python3.8/site-packages/pybuda/run/impl.py", line 414, in _initialize_pipeline
    _compile_devices(sequential, training=training, sample_inputs=sample_inputs, sample_targets=sample_targets, microbatch_count=microbatch_count, verify_cfg=verify_cfg)
  File "/home/smduck/Downloads/pyb-20-04/env/lib/python3.8/site-packages/pybuda/run/impl.py", line 1250, in _compile_devices
    raise RuntimeError(f"Compile failed for {d}")
RuntimeError: Compile failed for CPUDevice 'cpu0_fallback'
2024-04-16 05:21:39.861 | DEBUG    | pybuda.run.impl:_shutdown:1265 - PyBuda shutdown
2024-04-16 05:21:39.861 | DEBUG    | pybuda.run.impl:_shutdown:1281 - Waiting until processes done
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/smduck/Downloads/pyb-20-04/env/lib/python3.8/site-packages/pybuda/run/api.py", line 475, in shutdown
    return _shutdown()
  File "/home/smduck/Downloads/pyb-20-04/env/lib/python3.8/site-packages/pybuda/run/impl.py", line 1294, in _shutdown
    p.terminate()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 133, in terminate
    self._popen.terminate()
AttributeError: 'NoneType' object has no attribute 'terminate'

**Comment by milank94** [comment]
Hi @danindiana 

The version of pybuda you are running (v0.9.75) is not one of the stable released versions.

Could you please try on the latest stable release (v0.10.5) -- https://github.com/tenstorrent/tt-buda/releases/tag/v0.10.5.gs.240315

Before running it, check to see that the device is in a ok state by resetting the cores and trying the smoke test:

- `tt-smi -r 0`
- https://github.com/tenstorrent/tt-buda-demos/blob/main/first_5_steps/1_install_tt_buda.md#smoke-test

**Comment by danindiana** [comment]
Thanks for the link! Docker is up and running!

Howdy @milank94 so I attempted that pybuda build using 3.10.14 python on a fresh 20.04 build. 

$tt-smi -r 0
 Starting tensix reset on GS board at pci index 0 
 Lowering clks to safe value... 
 Beginning reset sequence... 
 Finishing reset sequence... 
 Returning clks to original values... 
 Finished tensix reset on GS board at pci index 0
 
 Re-initializing boards after reset.... 
 Detected Chips: 1
 Detecting ARC: |
 Detecting DRAM: |
 [] ETH: |
(tsmi) smduck@calisota:~/Downloads/tsmi/bin$ python3 --version
Python 3.10.14
(tsmi) smduck@calisota:~/Downloads/tsmi/bin$ 

![Screenshot_2024-04-16_18-46-34](https://github.com/tenstorrent/tt-buda-demos/assets/3030588/5e4c1cd2-fd65-4649-9d51-b15f9a768853)

**Comment by danindiana** [comment]
I guess on the heels of that q here is another one:

mkdir pybud
smduck@calisota:~/Downloads$ mv pybuda-v0.10.9.gs.240401-alpha-ubuntu-20-04-amd64-python3.8.zip /home/smduck/Downloads/pybud
smduck@calisota:~/Downloads$ cd pybud/
smduck@calisota:~/Downloads/pybud$ ls
pybuda-v0.10.9.gs.240401-alpha-ubuntu-20-04-amd64-python3.8.zip
smduck@calisota:~/Downloads/pybud$ unzip pybuda-v0.10.9.gs.240401-alpha-ubuntu-20-04-amd64-python3.8.zip 
Archive:  pybuda-v0.10.9.gs.240401-alpha-ubuntu-20-04-amd64-python3.8.zip
  inflating: manifest.yaml           
  inflating: pybuda-0.1.240401+dev.gs.c7ce1e7-cp38-cp38-linux_x86_64.whl  
  inflating: tvm-0.14.0+dev.tt.dfda3826c-cp38-cp38-linux_x86_64.whl  
  inflating: torchvision-0.16.0+fbb4cc5-cp38-cp38-linux_x86_64.whl  
  inflating: Dockerfile-release-ubuntu-20-04-amd64  
smduck@calisota:~/Downloads/pybud$ python3 -m venv env
smduck@calisota:~/Downloads/pybud$ source env/bin/activate
(env) smduck@calisota:~/Downloads/pybud$ pip install pybuda-0.1.240401+dev.gs.c7ce1e7-cp38-cp38-linux_x86_64.whl tvm-0.14.0+dev.tt.dfda3826c-cp38-cp38-linux_x86_64.whl 
Processing ./pybuda-0.1.240401+dev.gs.c7ce1e7-cp38-cp38-linux_x86_64.whl
ERROR: Invalid requirement: 'torch@ https://download.pytorch.org/whl/cpu-cxx11-abi/torch-2.1.0%2Bcpu.cxx11.abi-cp38-cp38-linux_x86_64.whl; python_version == "3.8"'
(env) smduck@calisota:~/Downloads/pybud$ python3 --version
Python 3.8.10
(env) smduck@calisota:~/Downloads/pybud$ deactivate 
smduck@calisota:~/Downloads/pybud$ python3.8 -m venv env38
smduck@calisota:~/Downloads/pybud$ source env38/bin/activate
(env38) smduck@calisota:~/Downloads/pybud$ python3 --version
Python 3.8.10

**Comment by milank94** [comment]
@danindiana Sorry I'm not clear on what the last comment is referring to or referencing.

Just some pointers:

- If you are using Ubuntu 20.04, then the compatible version of Python will be 3.8
- If you want to run from Docker, then please use the steps highlighted here: https://github.com/tenstorrent/tt-buda-demos/blob/main/first_5_steps/1_install_tt_buda.md#docker-container-installation
- You will first need to install the driver (tt-kmd), update firmware (tt-firmware / tt-flash), and setup Huge pages
- This is the command to run the Docker container: https://github.com/tenstorrent/tt-buda-demos/blob/main/first_5_steps/1_install_tt_buda.md#step-4-run-the-container. Please note this step which ensure that the device gets mapped from the container: `--device /dev/tenstorrent`

**Comment by milank94** [comment]
Closing issue for now due to inactivity. @danindiana please re-open if the issue persists.
